apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: firebase-graphql-docker-k8s
          image: firebase-graphql-docker-k8s
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  type: NodePort
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080