apiVersion: v1
kind: ConfigMap
metadata:
  name: architect-test-out-config
  namespace: default
data:
  # nginx
  UI_PROXY_PASS: "http://ui"
  UI_PROXY_HOST: "$host"
  # postgre-db
  PGRST_DB_USERNAME: "authenticator"
  PGRST_DB_SCHEMA: "api"
  PGRST_DB_ANON_ROLE: "web_anon"

---
apiVersion: v1
kind: Secret
metadata:
  name: architect-test-out-secret
data:
  # postgre-db
  DB_ROOT_PASSWORD: "cGFzc3dvcmQ=" # password
  DB_USERNAME: "cG9zdGdyZXM=" # postgres
  DB_HOST: "cG9zdGdyZXNxbC1zZXJ2aWNl" # postgresql-service
  PGRST_DB_PASSWORD: "bXlzZWNyZXRwYXNzd29yZA==" # mysecretpassword