apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql-client
  template:
    metadata:
      labels:
        app: psql-client
    spec:
      containers:
        - name: psql
          image: postgres:latest
          command: [ "sleep" ]
          args: [ "infinity" ]
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.33.1
          env:
            - name: INSTANCE_CONNECTION_NAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-instance-connection
                  key: INSTANCE_CONNECTION_NAME
          command: [ "/bin/sh", "-c" ]
          args:
            - "/cloud_sql_proxy --dir=/cloudsql --instances=$${INSTANCE_CONNECTION_NAME} --ip_address_types=PRIVATE"
          securityContext:
            runAsUser: 2
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql
          emptyDir: { }