apiVersion: apps/v1
kind: Deployment
metadata:
  name: psql-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psql-client
  template:
    metadata:
      labels:
        app: psql-client
    spec:
      containers:
        - name: psql
          image: postgres:latest
          command: [ "sleep" ]
          args: [ "infinity" ]
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: DB_HOST
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloudsql-db-credentials
                  key: DB_PASSWORD