apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: postgres-config
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
spec:
  type: ClusterIP
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000