apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  PGRST_DB_URI: "postgres://authenticator:mysecretpassword@postgresql-service:5432/postgres"
  PGRST_DB_SCHEMA: "api"
  PGRST_DB_ANON_ROLE: "web_anon"
  DATABASE_URL: "postgresql://postgres:password@postgresql-service:5432/postgres"
  POSTGRES_PASSWORD: "password"