apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest
          ports:
            - containerPort: 3000
          env:
            - name: PGRST_DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_USERNAME
                  name: architect-test-out-config
            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_ANON_ROLE
                  name: architect-test-out-config
            - name: PGRST_DB_SCHEMA
              valueFrom:
                configMapKeyRef:
                  key: PGRST_DB_SCHEMA
                  name: architect-test-out-config
            - name: PGRST_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PGRST_DB_PASSWORD
                  name: architect-test-out-secret
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  key: DB_HOST
                  name: architect-test-out-secret
            - name: PGRST_DB_URI
              value: "postgres://$(PGRST_DB_USERNAME):$(PGRST_DB_PASSWORD)@$(DB_HOST):5432/postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: postgrest-service
spec:
  type: ClusterIP
  selector:
    app: postgrest
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000