apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  PGRST_DB_USERNAME: "authenticator"
  PGRST_DB_SCHEMA: "api"
  PGRST_DB_ANON_ROLE: "web_anon"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
data:
  DB_ROOT_PASSWORD: "cGFzc3dvcmQ=" # password
  DB_USERNAME: "cG9zdGdyZXM=" # postgres
  DB_HOST: "cG9zdGdyZXNxbC1zZXJ2aWNl" # postgresql-service
  PGRST_DB_PASSWORD: "bXlzZWNyZXRwYXNzd29yZA==" # mysecretpassword