apiVersion: batch/v1
kind: Job
metadata:
  name: sqlalchemy-migration-job
spec:
  template:
    spec:
      containers:
        - name: sqlalchemy
          image: us-west2-docker.pkg.dev/fir-architect-test-out/architect-try-gar/sqlalchemy-migration-seed:latest
          envFrom:
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
      restartPolicy: Never
  backoffLimit: 4