apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      serviceAccountName: ghcr-sa
      containers:
        - name: firebase-graphql-docker-k8s
          image: us-west2-docker.pkg.dev/fir-architect-test-out/architect-try-gar/firebase-graphql-docker-k8s-test-out:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80":{"name": "graphql-neg"}}}'
spec:
  type: ClusterIP
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000