apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
        - name: firebase-graphql-docker-k8s
          image: gcr.io/firebase-architect-test-out/firebase-graphql-docker-k8s-test-out:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-service
spec:
  type: LoadBalancer
  selector:
    app: graphql
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000