name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: 'Auth to google clould'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
#       -
#         name: Login to Google Artifacts Registry
#         uses: docker/login-action@v3
#         with:
#           registry: us-west2-docker.pkg.dev
#           username: _json_key
#           password: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"
      - 
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
      -
        name: Configure Docker to use the Google Artifact Registry
        run: gcloud auth configure-docker us-west2-docker.pkg.dev # Change the region accordingly
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: graphql-api/.
          push: true
          # tags: ghcr.io/${{ github.repository }}:latest
          tags: us-west2-docker.pkg.dev/fir-architect-test-out/architect-try-gar/firebase-graphql-docker-k8s-test-out:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - 
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
      - 
        name: Deploy to GKE
        run: |
          kubectl apply -f graphql-api/k8s/graphql.yaml
