name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: 'Auth to google clould'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: access_token
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
          
      - 
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: gcr.io
          username: oauth2accesstoken
          password: "${{ steps.auth.outputs.access_token }}"
      - 
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - 
        name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: graphql-api/.
          push: true
          # tags: ghcr.io/${{ github.repository }}:latest
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/firebase-graphql-docker-k8s-test-out:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      # - 
      #   name: Get GKE credentials
      #   uses: 'google-github-actions/get-gke-credentials@v2'
      #   with:
      #     cluster_name: ${{ secrets.GKE_CLUSTER }}
      #     location: ${{ secrets.GKE_ZONE }}
      # - 
      #   name: Check and Delete Existing GHCR Secret
      #   run: |
      #     kubectl get secret ghcr-secret && kubectl delete secret ghcr-secret || echo "Secret does not exist"
      # - 
      #   name: Create Secret for GHCR
      #   run: |
      #     kubectl create secret docker-registry ghcr-secret \
      #       --docker-server=ghcr.io \
      #       --docker-username=${{ github.actor }} \
      #       --docker-password=${{ secrets.GITHUB_TOKEN }} \
      #       --docker-email=leonard.li.pub@gmail.com
      # - 
      #   name: Apply Service Account
      #   run: kubectl apply -f k8s/serviceaccount.yaml
      # - 
      #   name: Deploy to GKE
      #   run: |
      #     kubectl apply -f graphql-api/k8s/graphql.yaml
