name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - 
        name: Checkout repository
        uses: actions/checkout@v4
      # -
      #   name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      # - 
      #   name: Login to GitHub Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}
      # - 
      #   name: Build and push Docker image
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: graphql-api/.
      #     push: true
      #     tags: ghcr.io/${{ github.repository }}:latest
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max
      - 
        name: 'Auth to google clould'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - 
        name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
      - 
        name: 'Use gcloud CLI'
        run: 'gcloud info'
      - 
        name: Get GKE credentials
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: ${{ secrets.GKE_CLUSTER }}
          location: ${{ secrets.GKE_ZONE }}
      - 
        name: Deploy to GKE
        run: |
          kubectl set image deployment/your-deployment your-container=ghcr.io/${{ github.repository }}:latest
